#include "MQTTManager.h"
#include "Irrigation.h"
#include "config.h"
#include <WiFi.h>
#include <Preferences.h>
#include <PubSubClient.h>
MQTTManager MQTT; static WiFiClient net; static PubSubClient client(net); static Preferences prefs; static MQTTManager* self=nullptr;
void mqttCallbackBridge(char*t,byte*p,unsigned int l){if(self)self->callback(t,p,l);} static String ps(byte*p,unsigned int l){String s;for(unsigned int i=0;i<l;i++)s+=(char)p[i];s.trim();return s;} static bool yes(const String&s){return s.equalsIgnoreCase("ON")||s.equalsIgnoreCase("true")||s=="1";}
void MQTTManager::load(){if(!prefs.begin("mqtt",true))return;_broker=prefs.getString("broker","");_port=prefs.getUShort("port",1883);_user=prefs.getString("user","");_password=prefs.getString("pass","");prefs.end();}
void MQTTManager::save(){if(!prefs.begin("mqtt",false))return;prefs.putString("broker",_broker);prefs.putUShort("port",_port);prefs.putString("user",_user);prefs.putString("pass",_password);prefs.end();}
void MQTTManager::begin(){self=this;load();client.setCallback(mqttCallbackBridge);client.setKeepAlive(MQTT_KEEPALIVE_SEC);client.setBufferSize(2048);}
void MQTTManager::setBroker(const String&v){_broker=v;save();client.disconnect();_discoveryPublished=false;}void MQTTManager::setPort(uint16_t v){_port=v?v:1883;save();client.disconnect();_discoveryPublished=false;}void MQTTManager::setUser(const String&v){_user=v;save();client.disconnect();_discoveryPublished=false;}void MQTTManager::setPassword(const String&v){_password=v;save();client.disconnect();_discoveryPublished=false;}
bool MQTTManager::connected()const{return client.connected();}
bool MQTTManager::connect(){if(!WiFi.isConnected()||!_broker.length())return false;client.setServer(_broker.c_str(),_port);String id=String(DEVICE_NAME)+"-"+String((uint32_t)(ESP.getEfuseMac()&0xffffffff),HEX);String will=String(MQTT_BASE_TOPIC)+"/status/availability";bool ok=_user.length()?client.connect(id.c_str(),_user.c_str(),_password.c_str(),will.c_str(),0,true,"offline"):client.connect(id.c_str(),will.c_str(),0,true,"offline");if(!ok){Serial.printf("[MQTT] connect failed rc=%d\n",client.state());return false;}client.publish(will.c_str(),"online",true);client.subscribe(MQTT_BASE_TOPIC "/command/#");client.subscribe(MQTT_BASE_TOPIC "/zone/+/command");client.subscribe(MQTT_BASE_TOPIC "/zone/+/runtime/set");publishDiscovery();publishState();return true;}
void MQTTManager::loop(){if(!WiFi.isConnected()){if(client.connected())client.disconnect();return;}if(!client.connected()){if(millis()-_lastReconnect>=MQTT_RECONNECT_MS){_lastReconnect=millis();connect();}return;}client.loop();if(millis()-_lastPublish>=MQTT_PUBLISH_MS){_lastPublish=millis();publishState();}}
void MQTTManager::callback(char*t,byte*p,unsigned int l){String topic(t),v=ps(p,l);if(topic==String(MQTT_BASE_TOPIC)+"/command/start"){if(v.equalsIgnoreCase("CYCLE"))IRRIGATION.startCycle();else{int z=v.toInt();if(z>=1&&z<=MAX_ZONES)IRRIGATION.startZone(z-1);}}else if(topic==String(MQTT_BASE_TOPIC)+"/command/stop"){IRRIGATION.stopAll();}else if(topic==String(MQTT_BASE_TOPIC)+"/command/auto"){IRRIGATION.setAutoMode(yes(v));}else if(topic.startsWith(String(MQTT_BASE_TOPIC)+"/zone/")){int a=topic.indexOf("/zone/")+6,b=topic.indexOf('/',a);if(b<0)return;int z=topic.substring(a,b).toInt()-1;if(z<0||z>=MAX_ZONES)return;String action=topic.substring(b+1);if(action=="command"){if(yes(v))IRRIGATION.startZone(z);else IRRIGATION.stopAll();}else if(action=="runtime/set")IRRIGATION.setRuntime(z,constrain(v.toInt(),(long)MIN_RUNTIME_SEC,(long)MAX_RUNTIME_SEC));}publishState();}
void MQTTManager::publishState(bool retained){if(!client.connected())return;client.publish(MQTT_BASE_TOPIC "/status/state",IRRIGATION.stateText(),retained);String s=IRRIGATION.isRunning()?String(IRRIGATION.activeZone()+1):"0";client.publish(MQTT_BASE_TOPIC "/status/active_zone",s.c_str(),retained);s=String(IRRIGATION.remainingSeconds());client.publish(MQTT_BASE_TOPIC "/status/remaining_seconds",s.c_str(),retained);s=IRRIGATION.autoMode()?"ON":"OFF";client.publish(MQTT_BASE_TOPIC "/status/auto",s.c_str(),retained);for(uint8_t z=0;z<MAX_ZONES;z++){String t=String(MQTT_BASE_TOPIC)+"/zone/"+String(z+1)+"/state";const char*q=IRRIGATION.isRunning()&&IRRIGATION.activeZone()==z?"ON":"OFF";client.publish(t.c_str(),q,retained);t=String(MQTT_BASE_TOPIC)+"/zone/"+String(z+1)+"/runtime";s=String(IRRIGATION.runtime(z));client.publish(t.c_str(),s.c_str(),retained);}}
static void pub(const String&t,const String&j){client.publish(t.c_str(),j.c_str(),true);} void MQTTManager::publishDiscovery(){if(!client.connected()||_discoveryPublished)return;publishSwitchDiscovery();publishStatusDiscovery();for(uint8_t z=0;z<MAX_ZONES;z++){publishZoneDiscovery(z);publishNumberDiscovery(z);}_discoveryPublished=true;}
void MQTTManager::publishSwitchDiscovery(){String t=String(MQTT_DISCOVERY_PREFIX)+"/switch/gtg_beregening/auto/config";pub(t,"{\"name\":\"Beregening automatisch\",\"unique_id\":\"gtg_beregening_auto\",\"command_topic\":\"beregening/command/auto\",\"state_topic\":\"beregening/status/auto\",\"payload_on\":\"ON\",\"payload_off\":\"OFF\",\"device\":{\"identifiers\":[\"gtg_beregening\"],\"name\":\"GTG Beregening\",\"manufacturer\":\"GridTogether\",\"model\":\"ESP32-S3\"}}");}
void MQTTManager::publishStatusDiscovery(){String d="\"device\":{\"identifiers\":[\"gtg_beregening\"],\"name\":\"GTG Beregening\",\"manufacturer\":\"GridTogether\",\"model\":\"ESP32-S3\"}";pub(String(MQTT_DISCOVERY_PREFIX)+"/sensor/gtg_beregening/state/config","{\"name\":\"Beregening status\",\"unique_id\":\"gtg_beregening_state\",\"state_topic\":\"beregening/status/state\","+d+"}");pub(String(MQTT_DISCOVERY_PREFIX)+"/sensor/gtg_beregening/active_zone/config","{\"name\":\"Actieve zone\",\"unique_id\":\"gtg_beregening_active_zone\",\"state_topic\":\"beregening/status/active_zone\","+d+"}");pub(String(MQTT_DISCOVERY_PREFIX)+"/sensor/gtg_beregening/remaining/config","{\"name\":\"Resterende tijd\",\"unique_id\":\"gtg_beregening_remaining\",\"state_topic\":\"beregening/status/remaining_seconds\",\"unit_of_measurement\":\"s\",\"device_class\":\"duration\","+d+"}");}
void MQTTManager::publishZoneDiscovery(uint8_t z){String id="gtg_beregening_zone_"+String(z+1),t=String(MQTT_DISCOVERY_PREFIX)+"/switch/"+id+"/config";String j="{\"name\":\"Zone "+String(z+1)+"\",\"unique_id\":\""+id+"\",\"command_topic\":\"beregening/zone/"+String(z+1)+"/command\",\"state_topic\":\"beregening/zone/"+String(z+1)+"/state\",\"payload_on\":\"ON\",\"payload_off\":\"OFF\",\"device\":{\"identifiers\":[\"gtg_beregening\"],\"name\":\"GTG Beregening\",\"manufacturer\":\"GridTogether\",\"model\":\"ESP32-S3\"}}";pub(t,j);}
void MQTTManager::publishNumberDiscovery(uint8_t z){String id="gtg_beregening_zone_runtime_"+String(z+1),t=String(MQTT_DISCOVERY_PREFIX)+"/number/"+id+"/config";String j="{\"name\":\"Zone "+String(z+1)+" looptijd\",\"unique_id\":\""+id+"\",\"command_topic\":\"beregening/zone/"+String(z+1)+"/runtime/set\",\"state_topic\":\"beregening/zone/"+String(z+1)+"/runtime\",\"min\":10,\"max\":7200,\"step\":10,\"mode\":\"box\",\"unit_of_measurement\":\"s\",\"device\":{\"identifiers\":[\"gtg_beregening\"],\"name\":\"GTG Beregening\",\"manufacturer\":\"GridTogether\",\"model\":\"ESP32-S3\"}}";pub(t,j);}
