#include "WiFiConfig.h"
#include "MQTTManager.h"
#include "config.h"
#include <WiFi.h>
#include <Preferences.h>
#include <ElegantOTA.h>
WiFiConfig WiFiCfg;static Preferences p;
void WiFiConfig::load(){if(!p.begin("net",true))return;_ssid=p.getString("ssid","");_pass=p.getString("pass","");p.end();}void WiFiConfig::save(const String&s,const String&pw){if(!p.begin("net",false))return;p.putString("ssid",s);p.putString("pass",pw);p.end();_ssid=s;_pass=pw;}
void WiFiConfig::begin(){load();routes();if(_ssid.length())startSTA();else startAP();}
void WiFiConfig::startSTA(){_apActive=false;WiFi.mode(WIFI_STA);WiFi.setSleep(false);WiFi.begin(_ssid.c_str(),_pass.c_str());}
void WiFiConfig::startAP(){WiFi.mode(WIFI_AP_STA);_apSsid="GridTogether-"+String((uint32_t)(ESP.getEfuseMac()&0xffffff),HEX);WiFi.softAP(_apSsid.c_str(),"12345678");_dns.start(53,"*",WiFi.softAPIP());_apActive=true;Serial.printf("[WiFi] AP %s / 12345678 / %s\n",_apSsid.c_str(),WiFi.softAPIP().toString().c_str());}
bool WiFiConfig::connected()const{return WiFi.isConnected();}String WiFiConfig::ip()const{return WiFi.isConnected()?WiFi.localIP().toString():"";}
void WiFiConfig::routes(){_server.on("/",HTTP_GET,[this]{root();});_server.on("/scan",HTTP_GET,[this]{scan();});_server.on("/setwifi",HTTP_GET,[this]{setwifi();});_server.on("/mqtt",HTTP_GET,[this]{mqtt();});_server.on("/reboot",HTTP_GET,[this]{reboot();});_server.onNotFound([this]{_server.sendHeader("Location","/");_server.send(302,"text/plain","");});}
void WiFiConfig::root(){String h="<html><meta name='viewport' content='width=device-width'><body style='font-family:Arial;background:#111;color:#eee;padding:20px'><h1>GTG Beregening</h1><p>Firmware "+String(FW_VERSION)+"</p><p>WiFi: "+String(WiFi.isConnected()?"verbonden":"niet verbonden")+"</p>";if(WiFi.isConnected())h+="<p>IP: "+WiFi.localIP().toString()+"</p>";if(_apActive)h+="<p>AP: "+_apSsid+" / 12345678<br>"+WiFi.softAPIP().toString()+"</p>";h+="<h2>WiFi</h2><form action='/setwifi'><input name='ssid' placeholder='SSID'><input name='pass' type='password' placeholder='Wachtwoord'><button>Opslaan</button></form><h2>MQTT</h2><form action='/mqtt'><input name='broker' placeholder='Broker' value='"+MQTT.broker()+"'><input name='port' value='"+String(MQTT.port())+"'><input name='user' placeholder='Gebruiker' value='"+MQTT.user()+"'><input name='pass' type='password' placeholder='Wachtwoord'><button>Opslaan</button></form><p>MQTT: "+String(MQTT.connected()?"verbonden":"niet verbonden")+"</p><p><a href='/scan'>WiFi scan</a> | <a href='/update'>OTA</a> | <a href='/reboot'>Herstart</a></p></body></html>";_server.send(200,"text/html; charset=utf-8",h);}
void WiFiConfig::scan(){int n=WiFi.scanNetworks(false,true);String j="[";for(int i=0;i<n;i++){if(i)j+=",";j+="{\"ssid\":\""+WiFi.SSID(i)+"\",\"rssi\":"+String(WiFi.RSSI(i))+"}";}j+="]";WiFi.scanDelete();_server.send(200,"application/json",j);}
void WiFiConfig::setwifi(){if(!_server.hasArg("ssid")){_server.send(400,"text/plain","SSID ontbreekt");return;}save(_server.arg("ssid"),_server.hasArg("pass")?_server.arg("pass"):"");_server.send(200,"text/plain","WiFi opgeslagen; herstart...");delay(300);ESP.restart();}
void WiFiConfig::mqtt(){if(!_server.hasArg("broker")){_server.send(400,"text/plain","Broker ontbreekt");return;}MQTT.setBroker(_server.arg("broker"));if(_server.hasArg("port"))MQTT.setPort(_server.arg("port").toInt());if(_server.hasArg("user"))MQTT.setUser(_server.arg("user"));if(_server.hasArg("pass"))MQTT.setPassword(_server.arg("pass"));_server.sendHeader("Location","/");_server.send(302,"text/plain","");}
void WiFiConfig::reboot(){_server.send(200,"text/plain","Herstart...");delay(300);ESP.restart();}
void WiFiConfig::loop(){if(_apActive)_dns.processNextRequest();_server.handleClient();ElegantOTA.loop();static uint32_t retry=0;if(!_apActive&&!WiFi.isConnected()&&millis()-retry>15000){retry=millis();WiFi.disconnect();WiFi.begin(_ssid.c_str(),_pass.c_str());}if(WiFi.isConnected()&&_apActive){_dns.stop();WiFi.softAPdisconnect(true);WiFi.mode(WIFI_STA);_apActive=false;}}
